version: "3"
services:
  clasp:
    build:
      context: .
      dockerfile: Clasp.dockerfile
    entrypoint: /bin/bash
    working_dir: /app
    tty: true
    ports: 
      - "8080:8080"
    volumes:
      - "./config:/home/node"
      - "./app:/app"
